name: CVEarity SBOM Discovery
'on':
  repository_dispatch:
    types:
    - cvearity_sbom_scan
    - cvearity_iac_bom_scan
    - cvearity_ai_bom_scan
jobs:
  discovery:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.client_payload.branch || github.event.repository.default_branch
          }}
    - name: Run SBOM scan container
      run: "docker run --rm \\\n  -v ${{ github.workspace }}:/app/workspace \\\n \
        \ -e CVEARITY_API_URL=\"${{ github.event.client_payload.api_url }}\" \\\n\
        \  -e CVEARITY_UPLOAD_TOKEN=\"${{ github.event.client_payload.upload_token\
        \ }}\" \\\n  -e SCAN_ID=\"${{ github.event.client_payload.scan_id || '0' }}\"\
        \ \\\n  -e TARGET_PATH=\"/app/workspace\" \\\n  bhanugoudm041/testcdx:latest"
